before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh


stages:
  - build

job 0:
  stage: build
  script:
    - git pull origin master
    - genisoimage -output /var/lib/libvirt/images/iso-files -volid cidata -joliet -rock user-data meta-data
